language: node_js
node_js:
  - "16"
  - "14"
  - "12"

before_script:
  # Configure `git` user
  - git config --global user.email "foundry-test@mailinator.com"
  - git config --global user.name "Foundry Test"

notifications:
  email: false
