language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"

before_script:
  # Configure `git` user
  - git config --global user.email "foundry-test@mailinator.com"
  - git config --global user.name "Foundry Test"

notifications:
  email: false
